
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Volkan Tuyji  ## put your name
title: 'Software Developer &amp; Architect'  ## your title
location: Istanbul, Turkey


## Social Profiles
linkedin: https://www.linkedin.com/in/volkantuyji/  ## your linkedin account url
github: https://github.com/Tuyji  ## you dribbble account url
medium: https://medium.com/@tjwolkan  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
